[package]
name = "tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
bitfields = { path = "../bitfields" }
ahash.workspace = true
ariadne.workspace = true

